from django.db import models
from django.contrib.auth.models import AbstractUser



# Create your models here.



class userProfile(AbstractUser):
    nickname = models.CharField(max_length=50,blank=True,null=True)    
    phone = models.CharField(max_length=20, default='')
    role = models.CharField(max_length=10, default='user', choices=(('user', '普通用户'), ('admin', '管理员'), ('vip', 'VIP')))
    companyname = models.CharField(max_length=16,blank=True,null=True) 
    remarks = models.TextField(blank=True,null=True)    
    last_active = models.DateField(auto_now_add=True)
    created_time = models.DateTimeField(auto_now_add=True)
    hyperlink = models.CharField(max_length=16,blank=True,null=True,default="点击查看详细信息") 
    
    class Meta:
        db_table = 'auth_user'
        

class companyInfo(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.ForeignKey(userProfile,blank=True,null=True)
    companyname = models.CharField(max_length=64,blank=True,null=True)
    
#��ҵͳ�Ʊ�
class statistics(models.Model):
    id = models.AutoField(primary_key=True)
    company = models.ForeignKey(companyInfo,blank=True,null=True)
    organizationCode = models.CharField(max_length=16,blank=True,null=True)
    areaNumber = models.CharField(max_length=16,blank=True,null=True)
    enterpriseName = models.CharField(max_length=16,blank=True,null=True)
    natureOfCorporation = models.CharField(max_length=16,blank=True,null=True)
    corporateGender = models.IntegerField(blank=True,null=True)
    birthday = models.DateTimeField(blank=True,null=True)
    education = models.IntegerField(blank=True,null=True)
    address = models.CharField(max_length=64,blank=True,null=True)
    postalCode = models.IntegerField(blank=True,null=True)
    registeredAddress = models.CharField(max_length=64,blank=True,null=True)
    manager = models.CharField(max_length=16,blank=True,null=True)
    telephone = models.IntegerField(blank=True,null=True)
    fax = models.IntegerField(blank=True,null=True)
    statisticalControlOfficer = models.CharField(max_length=16,blank=True,null=True)
    preparedBy = models.CharField(max_length=16,blank=True,null=True)
    preparedByTelephone = models.CharField(max_length=16,blank=True,null=True)
    fillingTime = models.DateTimeField(blank=True,null=True)
    email = models.EmailField()
    url = models.CharField(max_length=16,blank=True,null=True)
    preparedByMobilephone = models.CharField(max_length=16,blank=True,null=True)
    
#��ҵ�ſ���
class company(models.Model):
    id = models.AutoField(primary_key=True)
    company = models.ForeignKey(companyInfo,blank=True,null=True)
    qb07_2 = models.CharField(max_length=64,blank=True,null=True)
    qb07_3 = models.CharField(max_length=64,blank=True,null=True)
    qb08 = models.TextField(max_length=64,blank=True,null=True) 
    qb21 = models.TextField(max_length=64,blank=True,null=True)
    qb22 = models.TextField(max_length=64,blank=True,null=True)
    qb101 = models.TextField(max_length=64,blank=True,null=True)
    qb03_0 = models.TextField(max_length=64,blank=True,null=True)
    qb03_1 = models.TextField(max_length=64,blank=True,null=True)
    qb04 = models.TextField(max_length=64,blank=True,null=True)
    qb04_0 = models.TextField(max_length=64,blank=True,null=True)
    qb20_1 = models.TextField(max_length=64,blank=True,null=True)
    qb20 = models.TextField(max_length=64,blank=True,null=True)
    qb06 = models.TextField(max_length=64,blank=True,null=True)
    qb06_1 = models.TextField(max_length=64,blank=True,null=True)
    qb06_2 = models.TextField(max_length=64,blank=True,null=True)
    qb18 = models.TextField(max_length=64,blank=True,null=True)
    qb09 = models.TextField(max_length=64,blank=True,null=True)
    qb10 = models.TextField(max_length=64,blank=True,null=True)
    qb11 = models.TextField(max_length=64,blank=True,null=True)
    qb13 = models.TextField(max_length=64,blank=True,null=True)
    qb12 = models.TextField(max_length=64,blank=True,null=True)
    qb14 = models.TextField(max_length=64,blank=True,null=True)
    qb14_1 = models.TextField(max_length=64,blank=True,null=True)
    qb14_2 = models.TextField(max_length=64,blank=True,null=True)
    qb15 = models.TextField(max_length=64,blank=True,null=True)
    qb15_1 = models.TextField(max_length=64,blank=True,null=True)
    qb15_2 = models.TextField(max_length=64,blank=True,null=True)
    qb15_3 = models.TextField(max_length=64,blank=True,null=True)
    qb15_4 = models.TextField(max_length=64,blank=True,null=True)
    qb15_5 = models.TextField(max_length=64,blank=True,null=True)
    qb16 = models.TextField(max_length=64,blank=True,null=True)
    qb16_1 = models.TextField(max_length=64,blank=True,null=True)
           
    
#���øſ���
class economic(models.Model):
    id = models.AutoField(primary_key=True)
    company = models.ForeignKey(companyInfo,blank=True,null=True)
    qc02 = models.CharField(max_length=64,blank=True,null=True)
    qc02_05 = models.CharField(max_length=64,blank=True,null=True)
    qc55 = models.CharField(max_length=64,blank=True,null=True)
    qc06 = models.CharField(max_length=64,blank=True,null=True)
    qc06_1 = models.CharField(max_length=64,blank=True,null=True)
    qc06_2 = models.CharField(max_length=64,blank=True,null=True)
    qc06_3 = models.CharField(max_length=64,blank=True,null=True)
    qc06_4 = models.CharField(max_length=64,blank=True,null=True)
    qc07 = models.CharField(max_length=64,blank=True,null=True)
    qc09 = models.CharField(max_length=64,blank=True,null=True)
    qc10 = models.CharField(max_length=64,blank=True,null=True)
    qc49 = models.CharField(max_length=64,blank=True,null=True)
    qc52 = models.CharField(max_length=64,blank=True,null=True)
    qc11 = models.CharField(max_length=64,blank=True,null=True)
    qc38 = models.CharField(max_length=64,blank=True,null=True)
    qc11_1 = models.CharField(max_length=64,blank=True,null=True)
    qc220 = models.CharField(max_length=64,blank=True,null=True)
    qc220_1 = models.CharField(max_length=64,blank=True,null=True)
    qc221 = models.CharField(max_length=64,blank=True,null=True)
    qc222 = models.CharField(max_length=64,blank=True,null=True) 
    qc223 = models.CharField(max_length=64,blank=True,null=True)
    qc223_2 = models.CharField(max_length=64,blank=True,null=True)
    qc223_3 = models.CharField(max_length=64,blank=True,null=True)
    qc224 = models.CharField(max_length=64,blank=True,null=True)
    qc228 = models.CharField(max_length=64,blank=True,null=True)
    qc229 = models.CharField(max_length=64,blank=True,null=True)
    qc225 = models.CharField(max_length=64,blank=True,null=True)
    qc233 = models.CharField(max_length=64,blank=True,null=True)
    qc232 = models.CharField(max_length=64,blank=True,null=True)
    qc120 = models.CharField(max_length=64,blank=True,null=True)
    qc227 = models.CharField(max_length=64,blank=True,null=True)
    qc230 = models.CharField(max_length=64,blank=True,null=True)
    qc234 = models.CharField(max_length=64,blank=True,null=True)
    qc12 = models.CharField(max_length=64,blank=True,null=True)
    qc231 = models.CharField(max_length=64,blank=True,null=True)
    qc13 = models.CharField(max_length=64,blank=True,null=True)  
    qc14 = models.CharField(max_length=64,blank=True,null=True)
    qc16 = models.CharField(max_length=64,blank=True,null=True)
    qc17 = models.CharField(max_length=64,blank=True,null=True)
    qc18 = models.CharField(max_length=64,blank=True,null=True)
    qc20 = models.CharField(max_length=64,blank=True,null=True)
    qc20_1 = models.CharField(max_length=64,blank=True,null=True)
    qc20_2 = models.CharField(max_length=64,blank=True,null=True)
    qc20_3 = models.CharField(max_length=64,blank=True,null=True)
    qc62 = models.CharField(max_length=64,blank=True,null=True)
    qc51 = models.CharField(max_length=64,blank=True,null=True)
    qc24 = models.CharField(max_length=64,blank=True,null=True)
    qc25 = models.CharField(max_length=64,blank=True,null=True)
    qc27_1 = models.CharField(max_length=64,blank=True,null=True)
    qc29 = models.CharField(max_length=64,blank=True,null=True)  
    qc30 = models.CharField(max_length=64,blank=True,null=True)
    qc65 = models.CharField(max_length=64,blank=True,null=True)
    qc61 = models.CharField(max_length=64,blank=True,null=True)
    qc30 = models.CharField(max_length=64,blank=True,null=True)
    qc31 = models.CharField(max_length=64,blank=True,null=True)
    qc33 = models.CharField(max_length=64,blank=True,null=True)
    qc34 = models.CharField(max_length=64,blank=True,null=True)
    qc63 = models.CharField(max_length=64,blank=True,null=True)
    qc50 = models.CharField(max_length=64,blank=True,null=True)
    qc39 = models.CharField(max_length=64,blank=True,null=True)
    qc40 = models.CharField(max_length=64,blank=True,null=True)
    qc41 = models.CharField(max_length=64,blank=True,null=True)  
    QC226_1 = models.CharField(max_length=64,blank=True,null=True)
    QC226_2 = models.CharField(max_length=64,blank=True,null=True)
    QC226 = models.CharField(max_length=64,blank=True,null=True)                             
    
    
    
#��Ա�ſ���
class personnel(models.Model):
    id = models.AutoField(primary_key=True)
    company = models.ForeignKey(companyInfo,blank=True,null=True)
    qd01 = models.CharField(max_length=64,blank=True,null=True)
    qd03 = models.CharField(max_length=8,blank=True,null=True)
    qd25 = models.CharField(max_length=16,blank=True,null=True)
    qd21 = models.IntegerField(blank=True,null=True)
    qd26 = models.CharField(max_length=64,blank=True,null=True)
    qd14 = models.CharField(max_length=8,blank=True,null=True)
    qd05 = models.CharField(max_length=16,blank=True,null=True)
    qd18 = models.IntegerField(blank=True,null=True)
    qd06 = models.CharField(max_length=64,blank=True,null=True)
    qd07 = models.CharField(max_length=8,blank=True,null=True)
    qd08 = models.CharField(max_length=16,blank=True,null=True)
    qd09 = models.IntegerField(blank=True,null=True)
    qd30 = models.CharField(max_length=64,blank=True,null=True)
    qd31 = models.CharField(max_length=8,blank=True,null=True)
    qd32 = models.CharField(max_length=16,blank=True,null=True)
    qd33 = models.IntegerField(blank=True,null=True) 
    qd34 = models.IntegerField(blank=True,null=True)
    qd35 = models.CharField(max_length=64,blank=True,null=True)
    qd36 = models.CharField(max_length=8,blank=True,null=True)
    qd27 = models.CharField(max_length=16,blank=True,null=True)
    qd28 = models.IntegerField(blank=True,null=True)

    
#�Ƽ���Ŀ�ſ�    
class projects(models.Model):
    id = models.AutoField(primary_key=True) 
    company = models.ForeignKey(companyInfo,blank=True,null=True)
    projectName = models.CharField(max_length=64,blank=True,null=True)   
    projectFrom = models.CharField(max_length=64,blank=True,null=True)   
    developmentForm = models.CharField(max_length=64,blank=True,null=True)
    achievement = models.CharField(max_length=64,blank=True,null=True)
    economicGoals = models.CharField(max_length=64,blank=True,null=True)
    activityType = models.CharField(max_length=64,blank=True,null=True)
    startTime = models.DateTimeField(blank=True,null=True)
    endTime = models.DateTimeField(blank=True,null=True)
    personnel =  models.CharField(max_length=64,blank=True,null=True)
    time = models.CharField(max_length=64,blank=True,null=True)
    stage = models.CharField(max_length=64,blank=True,null=True)
    funds = models.IntegerField(blank=True,null=True)
    capital = models.IntegerField(blank=True,null=True)


class projectstmp(models.Model):
    id = models.AutoField(primary_key=True) 
    company = models.ForeignKey(companyInfo,blank=True,null=True)
    projectName = models.CharField(max_length=64,blank=True,null=True)   
    projectFrom = models.CharField(max_length=64,blank=True,null=True)   
    developmentForm = models.CharField(max_length=64,blank=True,null=True)
    achievement = models.CharField(max_length=64,blank=True,null=True)
    economicGoals = models.CharField(max_length=64,blank=True,null=True)
    activityType = models.CharField(max_length=64,blank=True,null=True)
    startTime = models.DateTimeField(blank=True,null=True)
    endTime = models.DateTimeField(blank=True,null=True)
    personnel =  models.CharField(max_length=64,blank=True,null=True)
    time = models.CharField(max_length=64,blank=True,null=True)
    stage = models.CharField(max_length=64,blank=True,null=True)
    funds = models.IntegerField(blank=True,null=True)
    capital = models.IntegerField(blank=True,null=True)
#�Ƽ���ſ�    
class activities(models.Model):
    id = models.AutoField(primary_key=True)
    company = models.ForeignKey(companyInfo,blank=True,null=True)
    qj09 = models.CharField(max_length=64,blank=True,null=True)
    qj67 = models.CharField(max_length=64,blank=True,null=True)
    qj09_1 = models.CharField(max_length=64,blank=True,null=True)
    qj09_2 = models.CharField(max_length=64,blank=True,null=True)
    qj09_3 = models.CharField(max_length=64,blank=True,null=True)
    qj20 = models.CharField(max_length=64,blank=True,null=True)
    qj23_1 = models.CharField(max_length=64,blank=True,null=True)
    qj23_2 = models.CharField(max_length=64,blank=True,null=True)
    qj23_3 = models.CharField(max_length=64,blank=True,null=True)
    qj23_4 = models.CharField(max_length=64,blank=True,null=True)
    qj23_6 = models.CharField(max_length=64,blank=True,null=True)
    qj23_7 = models.CharField(max_length=64,blank=True,null=True)
    qj33 = models.CharField(max_length=64,blank=True,null=True)
    qj33_1 = models.CharField(max_length=64,blank=True,null=True)
    qj33_2 = models.CharField(max_length=64,blank=True,null=True)
    qj33_4 = models.CharField(max_length=64,blank=True,null=True)
    qj33_3 = models.CharField(max_length=64,blank=True,null=True)
    qj23_5 = models.CharField(max_length=64,blank=True,null=True)
    qj250 = models.CharField(max_length=64,blank=True,null=True)
    qj251 = models.CharField(max_length=64,blank=True,null=True) 
    qj01 = models.CharField(max_length=64,blank=True,null=True)
    qj07_0 = models.CharField(max_length=64,blank=True,null=True)
    qj07_1 = models.CharField(max_length=64,blank=True,null=True)
    qj07_2 = models.CharField(max_length=64,blank=True,null=True)
    qj14_1 = models.CharField(max_length=64,blank=True,null=True)
    qj55 = models.CharField(max_length=64,blank=True,null=True)
    qj56 = models.CharField(max_length=64,blank=True,null=True)
    qj56_1 = models.CharField(max_length=64,blank=True,null=True)
    qj55_1 = models.CharField(max_length=64,blank=True,null=True)
    qj55_2 = models.CharField(max_length=64,blank=True,null=True)
    qj74 = models.CharField(max_length=64,blank=True,null=True)
    qj57 = models.CharField(max_length=64,blank=True,null=True)
    qj57_1 = models.CharField(max_length=64,blank=True,null=True)
    qj75 = models.CharField(max_length=64,blank=True,null=True)
    qj83 = models.CharField(max_length=64,blank=True,null=True)
    qj83_1 = models.CharField(max_length=64,blank=True,null=True)  
    qj82 = models.CharField(max_length=64,blank=True,null=True)
    qj73 = models.CharField(max_length=64,blank=True,null=True)
    qj73_2 = models.CharField(max_length=64,blank=True,null=True)
    qj73_1 = models.CharField(max_length=64,blank=True,null=True)
    qj23 = models.CharField(max_length=64,blank=True,null=True)
    qj24 = models.CharField(max_length=64,blank=True,null=True)
    qj70 = models.CharField(max_length=64,blank=True,null=True)
    qj71 = models.CharField(max_length=64,blank=True,null=True)
    qj72 = models.CharField(max_length=64,blank=True,null=True)
    qj99 = models.CharField(max_length=64,blank=True,null=True)
    qj90 = models.CharField(max_length=64,blank=True,null=True)
    qj92 = models.CharField(max_length=64,blank=True,null=True)
    qj102 = models.CharField(max_length=64,blank=True,null=True)
    qj25 = models.CharField(max_length=64,blank=True,null=True)  
    qj79 = models.CharField(max_length=64,blank=True,null=True)
    qj77 = models.CharField(max_length=64,blank=True,null=True)
    qj79_1 = models.CharField(max_length=64,blank=True,null=True)
    qj79_2 = models.CharField(max_length=64,blank=True,null=True)
    qj85 = models.CharField(max_length=64,blank=True,null=True)
    qj85_1 = models.CharField(max_length=64,blank=True,null=True)
    qj86 = models.CharField(max_length=64,blank=True,null=True)
    qj86_1 = models.CharField(max_length=64,blank=True,null=True)
    qj87 = models.CharField(max_length=64,blank=True,null=True)
    qj87_1 = models.CharField(max_length=64,blank=True,null=True)
    qj101 = models.CharField(max_length=64,blank=True,null=True)
    qj101_1 = models.CharField(max_length=64,blank=True,null=True)   
    qj100 = models.CharField(max_length=64,blank=True,null=True)  
    qj100_1 = models.CharField(max_length=64,blank=True,null=True)
    qj98_1 = models.CharField(max_length=64,blank=True,null=True)
    qj27_1 = models.CharField(max_length=64,blank=True,null=True)
    qj28_1 = models.CharField(max_length=64,blank=True,null=True)
    qj80_1 = models.CharField(max_length=64,blank=True,null=True)
    qj80 = models.CharField(max_length=64,blank=True,null=True)
    qj52 = models.CharField(max_length=64,blank=True,null=True)
    qj58 = models.CharField(max_length=64,blank=True,null=True)
    qj59 = models.CharField(max_length=64,blank=True,null=True)
    qj61 = models.CharField(max_length=64,blank=True,null=True)
    qj62 = models.CharField(max_length=64,blank=True,null=True)      